language: objective-c
osx_image: xcode9
env:
  global:
  - FRAMEWORK_NAME=MXSegmentedControl
before_install:
- brew update
- brew outdated carthage || brew upgrade carthage
install:
- gem install cocoapods
- gem install xcpretty --no-rdoc --no-ri --no-document --quiet
script:
- set -o pipefail && xcodebuild -project MXSegmentedControl.xcodeproj -scheme $FRAMEWORK_NAME -sdk iphonesimulator11.0 -configuration Release | xcpretty -c
- pod lib lint --quick
before_deploy:
- carthage build --no-skip-current
- carthage archive $FRAMEWORK_NAME
deploy:
  provider: releases
  api_key:
    secure: DlAex/6HeevmNsByR/9mMXsDaUXwfWF7PEY6S9wOw29kwbcbI64IQNip7sRnfI8CGuXUAYNYQf8IzLLUSJbWWzXaay2aJcIXbGt9fCkgn3UhK72piLZk+GZww+1/afPciHNorbiSg7Fgd1ZLPkuyzMtX895iFGSbTE9mEFHljQwlSQQv5tyGH6Kx76XFTpnehsfG/vM9WUReWw35kghSOF3uHtTDNpG7znDgmcHSy8Jyq65XwA3i3zE668VOq7i8pdatSuQ5FVZSuws4WOZcg642GpIkYAcvTgs3QzcdcL6N/Ulvl++9mM9RsOZIXey5zd/RI2LJbBisOUVfAORk57VI9LyDKHz0iuP8NS6wzZXumZ6kmI77QzwApBrb0BqKqECtKZgBOAqALWpcBdJx6gvKiUUhn+HQ+QbPGxqp128gFa+dfXiE4qpb9vKJMV7rPUIaSAeiBL3B0BgiGFu0pc2HGz/eFs1+q85hr7651i9FUfQEEn8owxnHr/nqCYNPkagKTxOdl0s3tPsfVjwQHPD/dEGWZP23aqXBtkFEb0wqQmyv7dehdxFD7246OLlyjsP3iCVBZt3nYXXzP/KnFgYljdQp3lIBK4OUDzknrwg6WgVyA6u4fri7eYDVuYTfxwwlwPpQT7VckaCeIHm4H5R6vHGMlsflqOR0g36TuZE=
  file: $FRAMEWORK_NAME.framework.zip
  skip_cleanup: true
  on:
    repo: maxep/MXSegmentedControl
    tags: true
